name: hpa-geogen
channels:
  - default
  - conda-forge
  - bioconda
dependencies:
  - git-annex
  - htslib
  - libcurl
  - pynvim
  - r
  - r-irkernel
  - r-biocmanager
  - r-svglite
  - r-tidyverse
  - r-remotes
  - r-xfun
  - r-rstan
  - r-sf
  - r-lwgeom
  - r-ggmap
  - r-ggrepel
  - r-ggforce
  - jupytext
  - jupyter
  - notebook
