name: hpa-geogen
channels:
  - default
  - conda-forge
  - bioconda
dependencies:
  - git-annex
  - htslib
  - jupyter
  - jupytext
  - libcurl
  - notebook
  - pynvim
  - r
  - r-biocmanager
  - r-ecodist
  - r-foreach
  - r-fossil
  - r-ggforce
  - r-ggmap
  - r-ggrepel
  - r-irkernel
  - r-lwgeom
  - r-raster
  - r-remotes
  - r-rnaturalearth
  - r-rnaturalearthdata
  - r-rstan
  - r-sf
  - r-svglite
  - r-tidyverse
  - r-vegan
  - r-xfun
# install.packages(c("ggspatial", "GGally", "gdm", "RColorBrewer", "conStruct"))
# BiocManager::install("SNPRelate")
# remotes::install_github("kdm9/constructhelpers")
